sudo: false
branches:
  only:
  - master
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_1c28f76428ef_key -iv $encrypted_1c28f76428ef_iv -in publish-key.enc -out publish-key -d -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:fhcflx/alt-pub.git
- git fetch origin -f gh-pages:gh-pages
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github
