sudo: false
branches:
  only:
  - pelican
language: python
before_install:
- git remote set-url origin https://github.com/fhcflx/alt-pub.git
- git fetch origin -f gh-pages:gh-pages
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github
