exclude: [README.md,.bundle,.git,_site,Gemfile,Gemfile.lock]
url: ''
index:
  en: index.html
  pt: index-pt.html
defaults:
  -
    values:
      author: "Francisco H C Felix, Juvenia B Fontenele"
      permalink:


markdown: kramdown
